In [1]:
import numpy as np
import pandas as pd
import random
import itertools 
import os

In [2]:
#load in list of simulations, convert ot binary
def load_process_simulations(file_path): 
    simulations = np.load(file_path)
    
    def int_to_bit(n):
        binary = bin(n)[2:] 
        return binary.zfill(52)
    
    binary_simulations = [int_to_bit(sim) for sim in simulations]             
    return binary_simulations

## Change below based on file path

In [12]:

#notebook_dir = Path().resolve()

#repo_dir = notebook_dir / 'Project Penney' / 'penney-game'

os.chdir('/Users/student/Desktop/fall 2024/Automation/Project Penney/penney-game/')

In [20]:
os.getcwd()

'/Users/student/Desktop/fall 2024/Automation/Project Penney/penney-game'

In [21]:

processed_sims = load_process_simulations('simulation/results.npy')

In [22]:
def variation1(deck, player1_sequence, player2_sequence):
    player1_cards = 0
    player2_cards = 0
    pile = 0
    
    for i in range(len(deck) - 2):
        current_sequence = deck[i:i+3]
        pile += 1
        if current_sequence == player1_sequence:
            player1_cards += pile
            pile = 0
        elif current_sequence == player2_sequence:
            player2_cards += pile
            pile = 0 
    return deck, player1_cards, player2_cards

In [23]:
def process_decks_v1(processed_sims):
    results = []  # Initialize results list

    # Loop through each deck in processed_sims
    for deck in processed_sims:
        all_sequences = [''.join(seq) for seq in itertools.product('01', repeat=3)]
        
        # Loop through all pairs of sequences
        for p1 in all_sequences:
            for p2 in all_sequences:
                if p1 != p2:
                    deck, p1_cards, p2_cards = variation1(deck, p1, p2)
                    seq_combo = f"{p1}, {p2}"

                    # Append results for the current combination
                    results.append({
                        'Deck': deck,
                        'Sequence Combo': seq_combo,
                        'Player 1 Cards': p1_cards,
                        'Player 2 Cards': p2_cards
                    })

    # Convert results to DataFrame
    df = pd.DataFrame(results)
    return df

In [24]:
df_v1 = process_decks_v1(processed_sims)

In [25]:
df_v1

,Deck,Sequence Combo,Player 1 Cards,Player 2 Cards
0,0001111101110110011000010011011011010100100101...,"000, 001",12,37
1,0001111101110110011000010011011011010100100101...,"000, 010",26,24
2,0001111101110110011000010011011011010100100101...,"000, 011",8,40
3,0001111101110110011000010011011011010100100101...,"000, 100",4,44
4,0001111101110110011000010011011011010100100101...,"000, 101",14,34
...,...,...,...,...
55999995,0111010111100011010011100001010011010001101101...,"111, 010",10,37
55999996,0111010111100011010011100001010011010001101101...,"111, 011",4,38
55999997,0111010111100011010011100001010011010001101101...,"111, 100",12,36
55999998,0111010111100011010011100001010011010001101101...,"111, 101",10,36
55999999,0111010111100011010011100001010011010001101101...,"111, 110",14,29

In [26]:
def variation2(deck, player1_sequence, player2_sequence):
    player1_tricks = 0
    player2_tricks = 0
    
    for i in range(len(deck) - 2):
        current_sequence = deck[i:i+3]
        if current_sequence == player1_sequence:
            player1_tricks += 1
        elif current_sequence == player2_sequence:
            player2_tricks += 1
    return deck, player1_tricks, player2_tricks

In [27]:
def process_decks_v2(processed_sims):
    results = []  # Initialize results list

    # Loop through each deck in processed_sims
    for deck in processed_sims:
        all_sequences = [''.join(seq) for seq in itertools.product('01', repeat=3)]
        
        # Loop through all pairs of sequences
        for p1 in all_sequences:
            for p2 in all_sequences:
                if p1 != p2:
                    deck, p1_tricks, p2_tricks = variation2(deck, p1, p2)
                    seq_combo = f"{p1}, {p2}"

                    # Append results for the current combination
                    results.append({
                        'Deck': deck,
                        'Sequence Combo': seq_combo,
                        'Player 1 Tricks': p1_tricks,
                        'Player 2 Tricks': p2_tricks
                    })

    # Convert results to DataFrame
    df = pd.DataFrame(results)
    return df

In [28]:
df_v2 = process_decks_v2(processed_sims)
df_v2

,Deck,Sequence Combo,Player 1 Tricks,Player 2 Tricks
0,0001111101110110011000010011011011010100100101...,"000, 001",4,7
1,0001111101110110011000010011011011010100100101...,"000, 010",4,6
2,0001111101110110011000010011011011010100100101...,"000, 011",4,8
3,0001111101110110011000010011011011010100100101...,"000, 100",4,6
4,0001111101110110011000010011011011010100100101...,"000, 101",4,7
...,...,...,...,...
55999995,0111010111100011010011100001010011010001101101...,"111, 010",4,7
55999996,0111010111100011010011100001010011010001101101...,"111, 011",4,7
55999997,0111010111100011010011100001010011010001101101...,"111, 100",4,6
55999998,0111010111100011010011100001010011010001101101...,"111, 101",4,8
55999999,0111010111100011010011100001010011010001101101...,"111, 110",4,7

In [29]:
df_v1.to_csv('cards.csv')
df_v2.to_csv('tricks.csv')